# Ultralytics YOLO ğŸš€, AGPL-3.0 license
# DOTA8 dataset 8 images from split DOTAv1 dataset by Ultralytics
# parent
# â”œâ”€â”€ ultralytics
# â””â”€â”€ datasets
#     â””â”€â”€ data  â† downloads here (1MB)

# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: E:/aHieu/autotrain_YOLO/datasets/data # dataset root dir
train: E:/aHieu/autotrain_YOLO/datasets/data/images/train # train images (relative to 'path') 4 images
val: E:/aHieu/autotrain_YOLO/datasets/data/images/val # val images (relative to 'path') 4 images

# Classes
names:
  0: Cat
  1: Dog


